package com.example.service

import android.app.Notification
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import android.util.Log
import com.example.data.AppDatabase
import com.example.data.entity.CapturedNotification
import com.example.data.entity.NoteItem
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class NotificationReaderService : NotificationListenerService() {

    private val serviceScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    companion object {
        private const val TAG = "NotiReaderService"
        private val _isConnected = MutableStateFlow(false)
        val isConnected = _isConnected.asStateFlow()
    }

    override fun onListenerConnected() {
        super.onListenerConnected()
        _isConnected.value = true
        Log.d(TAG, "NotificationReaderService connected")
    }

    override fun onListenerDisconnected() {
        super.onListenerDisconnected()
        _isConnected.value = false
        Log.d(TAG, "NotificationReaderService disconnected")
    }

    override fun onNotificationPosted(sbn: StatusBarNotification?) {
        super.onNotificationPosted(sbn)
        if (sbn == null) return

        val pkgName = sbn.packageName ?: return
        // Ignore notifications generated by NotiNotas itself
        if (pkgName == packageName) return

        val notification = sbn.notification ?: return
        val extras = notification.extras ?: return

        serviceScope.launch {
            try {
                val db = AppDatabase.getDatabase(applicationContext)
                val monitoredApp = db.monitoredAppDao().getMonitoredApp(pkgName)

                // Only capture if user has marked this app to be monitored and enabled
                if (monitoredApp != null && monitoredApp.isEnabled) {
                    val title = extras.getCharSequence(Notification.EXTRA_TITLE)?.toString()?.trim() ?: ""
                    val bigText = extras.getCharSequence(Notification.EXTRA_BIG_TEXT)?.toString()?.trim()
                    val standardText = extras.getCharSequence(Notification.EXTRA_TEXT)?.toString()?.trim()
                    val text = if (!bigText.isNullOrBlank()) bigText else (standardText ?: "")
                    val subText = extras.getCharSequence(Notification.EXTRA_SUB_TEXT)?.toString()?.trim()

                    // Avoid saving blank notifications
                    if (title.isNotEmpty() || text.isNotEmpty()) {
                        val captured = CapturedNotification(
                            packageName = pkgName,
                            appName = monitoredApp.appName,
                            title = title.ifEmpty { monitoredApp.appName },
                            text = text,
                            subText = subText,
                            timestamp = if (sbn.postTime > 0) sbn.postTime else System.currentTimeMillis(),
                            isSavedAsNote = monitoredApp.autoSaveToNotes
                        )
                        db.capturedNotificationDao().insert(captured)

                        // If auto-save to notepad is enabled for this app, immediately create a note
                        if (monitoredApp.autoSaveToNotes) {
                            val noteContent = buildString {
                                append(text)
                                if (!subText.isNullOrBlank()) {
                                    append("\n\n")
                                    append(subText)
                                }
                            }
                            val note = NoteItem(
                                title = title.ifEmpty { "Nota de ${monitoredApp.appName}" },
                                content = noteContent,
                                sourcePackage = pkgName,
                                sourceAppName = monitoredApp.appName,
                                createdAt = System.currentTimeMillis(),
                                updatedAt = System.currentTimeMillis()
                            )
                            db.noteDao().insert(note)
                        }
                    }
                }
            } catch (e: Exception) {
                Log.e(TAG, "Error processing notification from $pkgName", e)
            }
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        _isConnected.value = false
        serviceScope.cancel()
    }
}
